import Head from 'next/head'
import App from './App'
import AddBusinessIcon from '@mui/icons-material/AddBusiness';


export default function Home() {

  const ico=<AddBusinessIcon/>;

  return (
    <div >
    
      <Head>
        <title>  Society Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <App/>

    </div>
  )
}
