import Head from 'next/head'
// import firebase from 'firebase/app'
import firebase from "firebase"

import { firebaseApp } from './services/firebase'


export default function Home() {
  const usersCollection = firebaseApp.firestore().collection("contacts")
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     

    </div>
  )
}
